name: orca
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.8
  - boost-cpp
  - uhd<=4.4.0 # Due to open bug with 4.5.0 and above: https://github.com/EttusResearch/uhd/issues/751
  - scipy
  - matplotlib
  - yaml-cpp=0.6.3
  - xarray
  - dask
  - zarr
  - hvplot
  - datashader
