name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment-rpi.yaml
          activate-environment: uhd
          python-version: 3.11.13

      - name: Run Tests in Conda Environment
        run: |
          conda activate uhd
          conda install -y pytest
          pytest tests/
        shell: bash -l
