name: Unit Tests

on:
  push:
  pull_request:

jobs:
  auto-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment-rpi.yaml
          activate-environment: uhd
          auto-activate-base: false
          python-version: 3.11.13

      - name: Cache Conda Environment
        uses: actions/cache@v3
        with:
          path: /home/runner/miniconda3/envs/uhd
          key: conda-env-full-${{ runner.os }}-${{ hashFiles('environment-rpi.yaml') }}-pytest
          restore-keys: |
            conda-env-full-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          conda run -n uhd python -c "import pytest" || conda run -n uhd conda install -y pytest
          sudo apt-get update && sudo apt-get install -y cmake g++ libboost-all-dev libuhd-dev uhd-host

      - name: Build and Install yaml-cpp
        run: |
          git clone https://github.com/jbeder/yaml-cpp.git
          cd yaml-cpp
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          make -j$(nproc)
          sudo make install

      - name: Build C++ Tests
        run: |
          cmake -S sdr -B build -DCMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu/cmake/UHD;/usr/local/lib/cmake/yaml-cpp"
          cmake --build build

      - name: Run Python Tests
        run: conda run -n uhd bash -c "PYTHONPATH=. pytest tests/"

      - name: Run C++ Tests
        run: ctest --test-dir build --output-on-failure --extra-verbose
