name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment-rpi.yaml
          activate-environment: uhd
          auto-activate-base: false
          python-version: 3.11.13

      - name: Install Pytest and Run Tests
        run: |
          conda install -y pytest
          pytest tests/
